name: Deploy-To-Production
on:
  push:
    branches:
      - master
jobs:
  Deploy-To-Production:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: npm run build
