name: Deploy-To-Production
on:
  push:
    branches:
      - master
jobs:
  Deploy-To-Production:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm test
      - run: npm run build --if-present
      - run: cp -r build /var/www/lime-otter
